### ISSUE TITLE
Chapter I

### ISSUE THREAD

**Issue by carmonamateo** [carmonamateo/Jouanolou#5]
**Transcription**
- [x] 7.2.2, l. 9: la sous-catégorie plaine (-> pleine)
- [x] 5.5 and 5.6: E\times F' should be E\otimes F'

**Original**

**Comment by BrKahn** [comment]
A few typos I noticed:
2.1: italic N should be bold N (several times).
5.5 and 5.6: E\times F' should be E\otimes F'
7.2.2, l. 9: la sous-catégorie plaine (-> pleine)
7.4 and 7.5: many instances of superscript (i) (or (i-1) etc.) on top of lim. Some \limits - \nolimits ought to be used.

**Comment by carmonamateo** [comment]
Thank you so much for your comments @BrKahn !

I would like to take this opportunity to address two points about "contributions." Firstly, it's essential to clearly indicate when there's a change in the original text versus the transcription. For instance, regarding the typo "2.1: italic N should be bold N (several times)," it is highly likely that the Ns are unbolded in the original. To have a clear understanding of the changes, we must differentiate between them. This leads to the second point. It would be more efficient if @BrKahn or any other contributor were to make their suggestions directly in the source (by forking) and then create a "pull request" from there.

In any case, if you prefer to provide a list of suggestions, it would be more efficient to indicate the exact location of the items that require revision. For instance:
"...several times" - where exactly?
"many instances..." - where can these be found?

However, as mentioned earlier, it would be preferable to edit the text files with the suggestions using a "pull request" approach.

**Comment by BrKahn** [comment]
Dear Mateo,
I accepted to look for typos, but I am sorry that I cannot go check if they were in the original or not.

When I say `at several places’, it means that these spots are very easy to determine once they have been noticed. In other cases, as for the typo `plaine’, I write precisely where they are.

Finally, I don’t know what it means to `make [my] suggestions directly in the source (by forking) and then create a "pull request" from there’, and I am sorry (again) that I don’t have time to learn. 

So I am afraid that I will continue to mention typos in the same fashion.

I can also send them to you by email.

Sincerely,
B. Kahn

**Comment by carmonamateo** [comment]
Dear @BrKahn,

Your work is appreciated as it is. Finding typos and listing them is valuable help. 
My preceding commentary was supposed to serve future volunteers.

Best regards,
Mateo
